namespace SampleOOPApllication;

/***********************************************************
 * This class will represent a Person
 *
 *A class has data (attributes) and methods (behavior)
 * 
 * Atrributes: Name
 *             Height
 *             Weight
 *             Age
 *             Gender
 *             Eyecolor
 *             HairColor
 *
 *
 *
 * 
 ***************************************************************/


public class Person
{
   /***********************************************************
    *Instance variables identify attributes unique to an object of a class
    *
    * Usually private to protect access from outside access
    **************************************************************/

   private string _name;  // C# coding convenion is private variables start with _
   private int    _heightInInches;
   private double _weightInPounds;
   private int    _age;
   private string _gender;
   private string _eyeColor;
   private string _hairColor;
   
   /**************************************************************************
    * Properties to allow access to the data
    *
    *
    *
    * 


   public string Name  
   {
       get => _name;
       set => _name = value ?? throw new ArgumentNullException(nameof(value));
   }

   public int HeightInInches
   {
       get => _heightInInches;
       set => _heightInInches = value;
   }

   public double WeightInPounds
   {
       get => _weightInPounds;
       set => _weightInPounds = value;
   }

   public int Age
   {
       get => _age;
       set => _age = value;
   }

   public string Gender
   {
       get => _gender;
       set => _gender = value ?? throw new ArgumentNullException(nameof(value));
   }

   public string EyeColor
   {
       get => _eyeColor;
       set => _eyeColor = value ?? throw new ArgumentNullException(nameof(value));
       ******************************************************************************/
       
    /**********************************************************************************
    * COnstructors intialize the objects
    ************************************************************************************/
    public Person(string name, int heightInInches, double weightInPounds, int age, string gender, string eyeColor)
    {
        _name = name;
        _heightInInches = heightInInches;
        _weightInPounds = weightInPounds;
        _age = age;
        _gender = gender;
        _eyeColor = eyeColor;
    }
    
    /************************************************************************************
     * Methods overides for default behaviours we dont want
     *
     *ToStrings()
     * Equals()
     * GetHashCodes()
     *
     * DO NOT ACCEPT THE CODE GENERATED BY N IDE FOR THESE WITHOUT LOOKING AT IT
     ********************************************************************************/
    
    
}
